# Generated by Django 4.1.5 on 2023-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Seller', 'Seller'), ('Customer', 'Customer')], max_length=10, null=True),
        ),
    ]
