version: '3'

services:
  ecommerce-v2:
    container_name: ecommerce-v2
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "9111:8000"
    command: /start-django.sh
    depends_on:
      - ecommerce-db-v2
      - ecommerce-redis-v2

  ecommerce-db-v2:
    image: postgres:14
    container_name: ecommerce-db-v2
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "8888:5432"

  ecommerce-redis-v2:
    container_name: ecommerce-redis-v2
    image: redis:7
    ports:
      - "1112:6379"
