# Generated by Django 4.1.5 on 2023-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('ProcessInProgress', 'Processinprogress'), ('Paid', 'Paid'), ('Cancel', 'Cancel')], default='New', max_length=30),
        ),
    ]
